site_name: Auramana RPG
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
  palette:
    primary: 'brown'
    accent: 'deep orange'

nav:
  - Início: index.md
  - Sistema:
    - Raças: racas.md
    - Classes:
      - Visão Geral: classes.md
      - Arcanista: classes/arcanista.md
      - Batedor: classes/batedor.md
      - Elementalista: classes/elementalista.md
      - Guerreiro: classes/guerreiro.md
      - Inspirador: classes/inspirador.md
      - Inventor: classes/inventor.md
      - Sacerdote: classes/sacerdote.md
    - Origens: origens.md