site_name: Auramana RPG
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
  palette:
    primary: 'brown'
    accent: 'deep orange'

nav:
  - Início: indice.md
  - Sistema:
    - Raças: racas.md
    - Classes: classes.md
    - Origens: origens.md
  - Fichas:
    - Ficha Auramana: ficha.md
    - Ficha T20: ficha-t20.md
  - Regras: regras.md